spring:
  application:
    name: bank-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bankapi}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Kittu@2003}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  threads:
    virtual:
      enabled: true
  jwt:
    secret: ${JWT_SECRET:your-very-long-secret-key-at-least-32-chars}
    expiration: 86400000

server:
  port: 8080